# Generated by Django 4.2.7 on 2023-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_importfile_file_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importfile',
            name='id',
        ),
        migrations.AddField(
            model_name='importfile',
            name='file_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
