# Generated by Django 4.2.7 on 2023-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0003_remove_importfile_id_importfile_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file_image',
            field=models.ImageField(blank=True, default='images/questionmark.jpeg', null=True, upload_to='images/'),
        ),
    ]
