# Generated by Django 4.2.7 on 2023-12-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0004_alter_importfile_file_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
